title: Solo Gaming Appreciation Month
description: >- # this means to ignore newlines until "baseurl:"
        A community effort by the Lone Wolf Role-Playing Google+ community,
        SGAM occurs for the duration of November, and is dedicated to the 
        enjoyment of solitaire tabletop gaming.

        Use the #SGAM and #SGAM2018 tags on social media to join in!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sologamingmonth.com"

author:
  name: 'Solo Gaming Appreciation Month'
  email: gm@sologamingmonth.com
  gplus_username: communities/116965157741523529510
  github_username: sologamingmonth

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
paginate_path: news/page:num
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

#kramdown:
  # use Github Flavored Markdown
  #input: GFM
  # do not replace newlines by <br>s
  #hard_wrap: true

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
